# Generated by Django 3.2 on 2021-07-14 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_auto_20210711_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ideas.tag'),
        ),
    ]
