# Generated by Django 3.2 on 2021-07-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_alter_idea_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
