# Generated by Django 3.2 on 2021-07-14 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_alter_idea_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='tag_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ideas.tag'),
        ),
    ]
